// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"context"
	"github.com/google/wire"
	"github.com/yusufwib/be-test/config"
	"github.com/yusufwib/be-test/handler"
	"github.com/yusufwib/be-test/repository"
	"github.com/yusufwib/be-test/service"
	"github.com/yusufwib/be-test/utils/logger"
	"github.com/yusufwib/be-test/utils/mvalidator"
	"gorm.io/gorm"
)

// Injectors from dependency.go:

func NewDependency(context2 context.Context, logger mlog.Logger, validator mvalidator.Validator, Config *config.ConfigGroup, Database *gorm.DB) *Dependency {
	employeeRepository := repository.NewEmployeeRepository(Database, "")
	employeeService := service.NewEmployeeService(employeeRepository)
	iEmployeeHander := handler.NewEmployeeHandler(context2, logger, validator, employeeService)
	dependency := &Dependency{
		EmployeeHandler: iEmployeeHander,
	}
	return dependency
}

// dependency.go:

type Dependency struct {
	EmployeeHandler handler.IEmployeeHander
}

var setEmployeeHandler = wire.NewSet(repository.NewEmployeeRepository, service.NewEmployeeService, handler.NewEmployeeHandler)
